ethersync/ethersync

docs/decisions/03-process-structure.md

Does this seem reasonable to you?

Add proposal for ADR-03

---

docs/decisions/06-operational-transform-in-rust.md

- Summarize our decision for automerge as the chosen CRDT library
- add ADR 06 draft

ADR 06: ot-type rust libraries

---

docs/decisions/05-crdt-library.md

Here's my ADR-formatted summary of what we discussed internally.

Summarize our decision for automerge as the chosen CRDT library

---

docs/ethersync-cli-ui.md

Based on our brainstorming and notes, documenting the desired UI.

Document our initial CLI user interface

---

.github/workflows/integration.yml
.github/workflows/rust.yml
daemon/Cargo.lock
daemon/Cargo.toml
daemon/src/actors.rs
daemon/src/bin/fuzzer.rs
daemon/src/types.rs
flake.lock
flake.nix

This runs the fuzzer and the test suite in a Nix environment which has an Ethersync-enabled Neovim installed.

Add Nix setup to CI

---

docs/decisions/07-cursor-positions.md

This encapsulates findings and insights from #19.
No decision made yet. To be discussed :) Maybe there are also more than two options?

Add draft of ADR-07 about cursor positions

---

daemon/src/daemon.rs
daemon/src/editor.rs

During shutdown it's important to not expect open channels from each side. This PR
- doesn't panic when the DocumentActorHandle <-> DocumentActor channel is closed
- detects when the receiving end of the editor connection is closed (while failing sends) and de-registers the editor handle

Fixing broken CI by allowing more graceful shutdown

---

.github/workflows/vim-plugin.yml
.pre-commit-config.yaml
vim-plugin/.luacheckrc
vim-plugin/lua/changetracker.lua
vim-plugin/lua/cursor.lua
vim-plugin/plugin/ethersync.lua

The ideas in this PR
- be more consistent in our coding style. I have used the https://github.com/luarocks/lua-style-guide as an inspiration.
- switch from camelCase to snake_case where it made sense (it did in almost all places, `newText` being one exception)
- cut conditionals a bit [more short](https://github.com/luarocks/lua-style-guide#conditional-expressions)
- add more linting (to the CI action as well as to pre-commit)
- introduce `luacheck`
- note that I decided not to check for maximum line length, as I found [this argument](https://github.com/luarocks/lua-style-guide#line-lengths) convincing and I'm often a bit annoyed by having to cut lines. It does make sense in some places (like git commits), but here I'd be happy to comply with a style guide. 
- also I've exchanged the …

refactoring the vim plugin

---

vim-plugin/lua/cursor.lua

A more handmade attempt at resolving the remainder of issue #38.
Things that could be done nicer:

vim: Jump to location-s!, a first attempt.

---

daemon/Cargo.lock
daemon/Cargo.toml
daemon/src/bin/fuzzer.rs
daemon/src/daemon.rs
daemon/src/document.rs
daemon/src/types.rs

This is a simple solution for now:
- Create files by opening them in an Ethersync-enabled editor.
- Delete files by deleting them on disk; a file watcher will pick it up.

Implement adding and deleting files

---

daemon/src/daemon.rs
vim-plugin/plugin/ethersync.lua

Don't allow editors to "open" (and thus, share) ignored files

---

daemon/src/peer.rs

- **handle bogus automerge sync message more gracefully**
- **Fix signedness of sync message length in peer protocol**

peer stability

---

flake.nix

* Add nixpkgs overlay
* Separately package nvim plugin
* Provide ethersync on nvim PATH

Flake improvements

---

.github/workflows/integration.yml
.github/workflows/rust.yml
.github/workflows/vim-plugin.yml
flake.nix

This reverts commit a94e362, reversing changes made to c7690d3.
Turns out that it broke our CI.

Revert Nix flake improvement

---

daemon/Cargo.lock
daemon/Cargo.toml
daemon/src/bin/fuzzer.rs
daemon/src/connect.rs
daemon/src/daemon.rs
daemon/src/main.rs
daemon/src/peer.rs

Make connections using libp2p

---

vim-plugin/plugin/ethersync.lua

vim: Only start tracking buffer if "open" succeeds

---

.github/workflows/integration.yml
.github/workflows/rust.yml

- **Run fuzzer in release mode (should be faster)**
- **Also trigger rust workflow on vim plugin changes**

improve ci

---

README.md
docs/editor-plugin-dev-guide.md
tools/dummy-jsonrpc.py

- FAQ and usage instructions in README
- Clarifications in the editor dev guide

Documentation improvements

---

daemon/src/peer.rs

Just stop the run() loop, and return the error.
This can happen in the brief moment between the protocol_handler stopping, and the SyncActor task being terminated.

When the SyncActor fails sending a message, don't panic

---

docs/decisions/08-secure-connections.md

This would probably do as-is; but I think it could also still be expanded a bit. Let me know if you see "blind spots".
Ah, I didn't integrate your comment about the key durations yet, for example!

ADR 08: How to secure connections?

---

daemon/src/daemon.rs
daemon/src/document.rs

Fix initialization logic of Document

---

daemon/src/daemon.rs
daemon/src/document.rs
daemon/src/editor.rs
daemon/src/ot.rs
daemon/src/types.rs

Fixes #63.
This needs a surprising amount of changes in our different daemon functions.

Support multiple local editors

---

.github/workflows/general.yml

This PR ensures that the tests run for both of our supported operating systems.

Run tests on MacOS in addition to Ubuntu

---

daemon/integration-tests/README.md
daemon/integration-tests/tests/vim-plugin.rs
vim-plugin/lua/utils.lua

vim: Fix bug when inserting text ending with \n after last visible line

---

docs/decisions/09-multi-file.md

What I wrote on the train. Stopped writing it half-way, needs proof-reading and probably more content.

ADR 09: How to keep directory structures in sync?

---

.github/workflows/release.yml
daemon/Cargo.toml

Build & release binary in CI

---

daemon/src/jsonrpc_forwarder.rs

Also allow two newlines when sending to ethersync client

---

book/src/first-steps.md
daemon/Cargo.lock
daemon/Cargo.toml
daemon/integration-tests/Cargo.lock
daemon/src/main.rs

- **Update crates with `cargo update`**
- **Update crate versions found by `cargo outdated -wR`**
- **Improve doc and user error regarding project and config dir**

Cargo dependency update and copy edit

---

book/src/first-steps.md
daemon/Cargo.lock
daemon/Cargo.toml
daemon/integration-tests/Cargo.lock
daemon/src/main.rs
daemon/src/peer.rs

Print the command required to connect when starting

---

daemon/Cargo.lock
daemon/integration-tests/tests/fuzzer.rs
daemon/src/daemon.rs
daemon/src/main.rs

- **bump ethersync version in Cargo.lock**
- **Revert "add random flag for manual fuzzing"**

Drop --random flag (used only in development) and repower fuzzer

---

daemon/src/peer.rs

Also, complain if it isn't.
This prevents secret theft on multi-user systems.

Make sure that the keyfile is created with 600 permissions

---

daemon/src/sandbox.rs

Instead of panicing, now *really* return an error when canonicalizing fails.

Supplement PR #253 with some code that we apparently missed

---

vscode-plugin/package.json
vscode-plugin/src/cursor.ts
vscode-plugin/src/extension.ts

- Fix percent encoding in file URIs
- Fix data loss situation when peer closes file without saving
- Add command to show other cursor positions (for screen readers)

VS Code improvements

---

CHANGELOG.md
daemon/Cargo.lock
daemon/Cargo.toml
daemon/integration-tests/Cargo.lock
vscode-plugin/DEVELOPMENT.md
vscode-plugin/package.json

Bump daemon to v0.6.0 and VS Code plugin to v0.2.1

---

book/src/configuration.md
book/src/connection-making.md
book/src/editor-plugin-dev-guide.md
book/src/first-steps.md
book/src/pair-programming.md
book/src/shared-notes.md
book/src/system-overview.md
book/src/workarounds.md
daemon/Cargo.lock
daemon/Cargo.toml
daemon/integration-tests/Cargo.lock
daemon/integration-tests/tests/fuzzer.rs
daemon/src/config.rs
daemon/src/daemon.rs
daemon/src/document.rs
daemon/src/editor.rs
daemon/src/lib.rs
daemon/src/logging.rs
daemon/src/main.rs
daemon/src/ot.rs
daemon/src/peer.rs
daemon/src/types.rs
daemon/src/wormhole.rs

Redesigning the CLI UI

---

.github/workflows/general.yml
.github/workflows/reuse.yml
daemon/Cargo.lock
daemon/Cargo.toml
daemon/integration-tests/Cargo.lock
daemon/integration-tests/Cargo.toml
daemon/integration-tests/tests/vim-plugin.rs
daemon/src/document.rs
daemon/src/types.rs
flake.lock
vim-plugin/lua/changetracker.lua

Let's see if this passes the CI?

Update flakes & crates, support + test Neovim 11

---

.github/workflows/deploy-nvim-plugin.yml
.github/workflows/release.yml

Fixes #320.
This is untested; the release action seems hard to test at this point. :/ But I hope it would work?

ci: Deploy nvim plugin to main only for releases; otherwise, to develop

---

nvim-plugin/README.md
nvim-plugin/lua/ethersync/cursor.lua
nvim-plugin/plugin/ethersync.lua

This is a first raw implementation of the follow mode, works on my machine :tm: (I'll try it with a coworker monday probably).
#58 
I don't mind changing a lot of stuff (rename, code convention,...) if you want.
Anyway, I can't wait for my coworker to come back from holidays to try ethersync in nvim!!!! 
Awesome project!
* I'm not really satisfied with the unfollow, I'd like to automatically unfollow when I type Esc, but I don't know how to do that, is it possible?
* In the readme, I updated the mappings examples but I think the keys I used are used by other plugins (I use Lazyvim and f and u are already mapped), which key combination should we set?

nvim: follow/unfollow participants

---

daemon/Cargo.lock
daemon/Cargo.toml
daemon/integration-tests/Cargo.lock

The idea is that everything is a little bit more efficient with the new automerge version :-)

bump automerge to 1.0.0-beta.3

---

daemon/Cargo.lock
daemon/Cargo.toml
daemon/integration-tests/Cargo.lock
daemon/src/daemon.rs
daemon/src/peer.rs
daemon/src/peer/sync.rs

daemon: Improve peer reconnection by optimistically reconnecting
