ethersync/ethersync

.pre-commit-config.yaml
docs/decisions/05-crdt-library.md
server/scripts/setupTypeScript.js

For my own sake (i have now multiple times missed to run the formatter before pushing my stuff), I have set up a pre-commit hook. I find this tool relatively convenient, but it's maybe too opinionated... (and adds a Python dependency to the dev tooling)
https://pre-commit.com/index.html
What do you think about it? Should we add it "for everyone"? If not, I can probably find a way to put my config elsewhere or git-ignore it...

Add pre-commit tooling configuration

---

daemon/src/actors.rs
daemon/src/bin/fuzzer.rs
daemon/src/client.rs
vim-plugin/lua/changetracker.lua
vim-plugin/lua/utils.lua
vim-plugin/plugin/ethersync.lua

This mainly pulls out the delta input/output logic into a helper file, removes unused/untested code, and adds the possibility to configure the socket via the `ETHERSYNC_SOCKET` environment variable.
This breaks our debug() in Vim, because the changetracker file doesn't have access to the `client`. It always was a bit weird anyway – maybe we should write it to a file, like [Vim's LSP feature does](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/log.lua)?

Clean up Vim plugin code

---

daemon/Cargo.lock
daemon/Cargo.toml
daemon/src/actors.rs
daemon/src/bin/fuzzer.rs
daemon/src/connect.rs
daemon/src/daemon.rs
daemon/src/editor.rs
daemon/src/lib.rs
daemon/src/main.rs
daemon/src/ot.rs
daemon/src/peer.rs
daemon/src/types.rs
vim-plugin/lua/changetracker.lua
vim-plugin/lua/utils.lua
vim-plugin/plugin/ethersync.lua

This PR introduces the first iteration of a multi-file feature. We're assuming that files are "static" (i.e. won't be renamed, added or removed after starting Ethersync) for simplicity.

Enable ethersync to work with multiple files

---

daemon/src/actors.rs
daemon/src/daemon.rs
daemon/src/editor.rs
daemon/src/types.rs
vim-plugin/lua/cursor.lua
vim-plugin/plugin/ethersync.lua

This PR adds a first iteration on cursor awareness. The decision on how to approach it can be found in ADR-07 (#23). This feature currently shows the cursor when it's there, but doesn't properly hide it again if a peer disconnects.

Basic Cursor Awareness in Vim synchronized through automerge

---

.github/workflows/integration.yml
.github/workflows/rust.yml
daemon/src/main.rs

This PR is probably suffering a bit from premature optimization. And also, I don't really know what I'm doing.
Basically I have switched from https://github.com/cachix/install-nix-action to https://github.com/DeterminateSystems/nix-installer-action + https://github.com/DeterminateSystems/magic-nix-cache-action.
The effect is that the two Action "Rust Daemon" and "Integration Test" are running a bit faster. Not the [promised](https://github.com/DeterminateSystems/magic-nix-cache-action) 30%+, but something like 20%? And it has magic in it's name! 🧙🏼 
Unscientific [science](https://xkcd.com/882/):
| Action           | Before this PR | In this PR | Relative decrease |
|------------------|----------------|------------|-------------------|
| [Rust …

Using another set nix github actions with the idea to speed up CI

---

daemon/src/actors.rs
daemon/src/connect.rs
daemon/src/daemon.rs
daemon/src/document.rs
daemon/src/editor.rs
daemon/src/types.rs
vim-plugin/lua/changetracker.lua
vim-plugin/plugin/ethersync.lua

In order to communicate error back to the editor, we need to implement JSON-RPC responses.
This PR brings does and uses them in a not-yet-sophisticated way in the neovim plugin: By printing it to the user.

editor jsonrpc requests

---

daemon/clippy.toml
daemon/src/bin/fuzzer.rs
daemon/src/connect.rs
daemon/src/daemon.rs
daemon/src/document.rs
daemon/src/jsonrpc_forwarder.rs
daemon/src/main.rs
daemon/src/ot.rs

Ran a bunch of clippy lints, mainly pedantic ones and improved things I saw while looking at the code.
I tried to split them into their own commits. Feel free to cherry-pick or deny some of them. I can rebase and remove commits if wished for.
A good idea might also be to [configure lints in the `Cargo.toml`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-lints-section).

Some lints and refactorings

---

daemon/src/daemon.rs

This avoids a bug where, if the user doesn't save a file, the file content and the CRDT content are inconsistent.
This fixes #65.

Write a file (if needed) after an editor sends "close"

---

daemon/src/actors.rs
vim-plugin/lua/utils.lua
vim-plugin/plugin/ethersync.lua

#110  has introduced a subtle bug. `open`ing a buffer always had a couple of side-effects that the tests are relying on. Now we need to acknowledge the `open` from the daemon (as we're, as of #110, only actually doing things in the plugin if the `open` was successful):
- starting the changetracker
- setting the correct EOL value
Additionally there seems to be an unexpected state: Through logging I have observed that when we open a buffer via the nvim library, it doesn't seem to be "loaded". When adding logging, it's possible to see that editing the file opens the buffer again. Probably through [this line](https://github.com/ethersync/ethersync/blob/fix-vim-tests/vim-plugin/lua/utils.lua#L48)?

Confirm plugin open in vim input test

---

daemon/src/bin/fuzzer.rs
daemon/src/peer.rs

It's unclear to me why, but using .cancelled() in the select! seems to block the other branches? Maybe using it in a loop is bad for some reason?
Hopefully fixes #125.

Instead of using a CancellationToken, directly abort the SyncActor task

---

daemon/src/bin/fuzzer.rs
daemon/src/daemon.rs
daemon/src/editor.rs
daemon/src/peer.rs
daemon/src/types.rs

This should make it easier to develop editor plugins, when you get feedback that your message couldn't get parsed.
Partial fix for #29.

When receiving faulty JSON-RPC on the socket, send an error back to the caller

---

daemon/Cargo.toml
daemon/src/main.rs
vim-plugin/plugin/ethersync.lua

It's much easier to set `ETHERSYNC_SOCKET` via the environment for many use cases instead of modifying the command line, as noted by @zormit in https://github.com/ethersync/ethersync/pull/112#issuecomment-2287008800. We currently do this by hand in the nvim plugin: https://github.com/ethersync/ethersync/blob/a41304aa0543077bcf8908d912dabf8bc91069cf/vim-plugin/plugin/ethersync.lua#L69-L72
We could do the same for the emacs plugin in #112, but it might be nice for the `ethersync` binary to support this itself.
- Add `"env"` feature to our `clap` dependency.
- Set [`Arg::env()`](https://docs.rs/clap/latest/clap/struct.Arg.html#method.env) for the global `socket_path: PathBuf` argument.
- A command-line `--socket-path` argument overrides this value; the env var is only read if the argument is …

make --socket-path pull ETHERSYNC_SOCKET from env via clap

---

daemon/Cargo.toml

It's possible to set [optimization flags](https://doc.rust-lang.org/cargo/reference/profiles.html) in cargo for the `--release` profile. This may make it slightly faster, and symbol stripping drastically reduces binary size (14M -> 7.2M):
```shell
> git checkout main
> cargo build --release
> ls target/release/ethersync
-rwxr-xr-x 2 cosmicexplorer wheel 14M Aug 14 08:14 target/release/ethersync*
> git checkout -
> cargo build --release
> ls target/release/ethersync
-rwxr-xr-x 2 cosmicexplorer wheel 7.2M Aug 14 08:08 target/release/ethersync*
```
Note that `opt-level` is [already set to 3 by default](https://doc.rust-lang.org/cargo/reference/profiles.html#release).

add optimization flags to --release profile

---

book/src/neovim.md
vim-plugin/plugin/ethersync.lua

The thing blocking us from using olding Neovim versions now are the `nvim_create_autocmd` functions.
Neovim v0.7 (the minimum required version) was released over three years ago in April 2022.
Lazy, for example, requires v8.0.
Fixes #56.

Support Neovim >=0.7

---

daemon/src/daemon.rs

A first attempt to approach #94. I guess we could then close the bug and open an enhancement issue that ask for syncing binary files.
Tested on our main repo. We see:
> INFO ThreadId(01) ethersync::daemon: Skipping non-text file /[...]/ethersync/book/src/git-integration-areas.png

fix: ignore files that could not be parsed as UTF-8 string

---

book/src/editor-plugin-dev-guide.md
daemon/integration-tests/tests/vim-plugin.rs
daemon/src/editor_connection.rs
daemon/src/types.rs
tools/dummy-jsonrpc.py
vim-plugin/plugin/ethersync.lua
vscode-plugin/src/extension.ts

This makes both creating and consuming the "edit" messages easier.

Make "edit" messages contain revision and delta on the top level

---

CHANGELOG.md
daemon/Cargo.toml
daemon/integration-tests/Cargo.lock
vscode-plugin/package.json

Breaking changes:
- "edit" messages now contain the revision and the delta on the top level, to avoid unnecessary nesting.
New features:
- We have installable packages on crates.io and on the Arch User Repository.
- Lower mimimum supported Neovim version from 0.10 to 0.7.
- Released a VS Code plugin!
- When there is no persisted CRDT document, load a structure that's compatible with other peers. This allows peers to start up individually, and sync up later.
- Persist changes to CRDT incrementally, instead of saving the entire document each time. This gives a big performance boost.
Bug fixes:
- Does not crash when binary files exist by ignoring them.

Bump daemon version to 0.5.0

---

daemon/integration-tests/README.md
daemon/integration-tests/tests/fuzzer.rs
daemon/integration-tests/tests/vim-plugin.rs
daemon/src/editor.rs
daemon/src/main.rs
daemon/src/sandbox.rs
flake.lock

We do this by making sure that the directory containing the socket is only accessible by the current user. The default directory is $XDG_RUNTIME_DIR.
Rename --socket-path to --socket-name.
Fixes #241.

Make sure the socket can't be accessed by other users

---

book/src/configuration.md
book/src/pair-programming.md
daemon/src/main.rs
daemon/src/peer.rs

Using it will leak the secret with other users on the same system. The only way to provide a secret now is via the config file.

Remove the --secret command line argument for security reasons

---

book/src/editor-plugin-dev-guide.md

As correctly pointed out by @schrieveslaach, thanks!

doc: The userid in a cursor message is currently a string, not an integer

---

.github/workflows/general.yml

This improves a couple of things about the way we build and test on the CI. A huge part of our CI time is spent compiling our dependencies, so:
- If testing fails, still cache the compiled dependencies.
- Cache dependencies of the integration-test crate, as well.
- If one of our matrix tests fails, don't abort the others (I think I would still be interested to see the other results!)
- In the `test` profile, don't generate debug information (would make output larger)
Full rebuild:
Using the cached dependencies:
Some more thoughts:
- I tried installing the mold linker, but it didn't seem to make a difference here.
- The cache action will not be used as soon as there's a change in Cargo.toml or Cargo.lock. I wonder whether we could simplify it to *always* cache the target directories. That …

Make CI builds faster

---

book/src/editor-plugin-dev-guide.md
book/src/first-steps.md
book/src/git-integration.md
book/src/pair-programming.md
book/src/shared-notes.md
book/src/workarounds.md
daemon/integration-tests/Cargo.toml
daemon/integration-tests/src/actors.rs
daemon/integration-tests/src/lib.rs
daemon/integration-tests/src/socket.rs
daemon/integration-tests/tests/fuzzer.rs
daemon/integration-tests/tests/vim-plugin.rs
daemon/src/config.rs
daemon/src/daemon.rs
daemon/src/editor.rs
daemon/src/logging.rs
daemon/src/main.rs
daemon/src/sandbox.rs
vim-plugin/plugin/ethersync.lua
vscode-plugin/package-lock.json
vscode-plugin/src/extension.ts

This has the advantage that two daemons started on different directories will never clash - useful for multi-daemon scenarios, and for local testing.
One downside is that the editor plugins need to do a bit more work: They need to figure out which directory to start `ethersync client` in. However, our two plugins already had all the code required to find it, because they needed to scan for the .ethersync directory anyway.
The --directory flag would be global for all subcommands.
What do you think? I think this is worth the additional editor code, and simplifies things a lot.
- Maybe we should drop this permission requirement now? I think basically all other programs leave it up to the user to set permissions on files in their own directories like they want... I did that for now in this …

Use .ethersync/socket as daemon socket

---

daemon/src/peer.rs

The most likely reason is someone talking trash to the QUIC port. No reason for us to crash.
This fixes #289.

When accepting a connection fails, log error instead of panicking

---

book/src/neovim.md
vim-plugin/plugin/ethersync.lua

Move the information into the documentation. I think it belongs there, it's such a minor issue that we don't need to display it at every startup.
In addition, in narrow terminal windows, the message forces the user to press "Enter" to acknowledge it, which is probably more annoying than being surprised by the changed option.

vim: Don't print message that we're disabling 'autoread' on each startup

---

daemon/integration-tests/tests/vim-plugin.rs
vim-plugin/lua/changetracker.lua

We saw these when pressing backspace on an empty line, or when using formatters, see #290.

vim: Don't send out deltas that don't change anything

---

.github/workflows/deploy-vim-plugin.yml
book/src/neovim.md

This PR sets up a CI action that deploys the vim-plugin/ to ethersync/ethersync-vim automatically (on commits on main).
This repo has a [repository secret](https://github.com/ethersync/ethersync/settings/secrets/actions) that's a new SSH private key, and the ethersync-vim has a corresponding public key configured as a [deploy key](https://github.com/ethersync/ethersync-vim/settings/keys).
I also updated the book, and added a config snippet for pckr.nvim (see #207).

Mirror contents of vim-plugin/ to ethersync/ethersync-vim

---

vim-plugin/lua/cursor.lua

vim: From version 0.11, use show_document instead of jump_to_location

---

vscode-plugin/src/cursor.ts
vscode-plugin/src/extension.ts

Addresses some points from #206:
- Position remote cursors between characters better
- Improve displaying of remote cursors (allow multiple ones, update them when switching between files)
- Show name of remote cursors in hover text
Still missing:

vscode: Improve display of remote cursors

---

book/src/workarounds.md
daemon/src/path.rs

Give better error message when clients try to open files outside base_dir

---

daemon/Cargo.lock
daemon/Cargo.toml
daemon/integration-tests/Cargo.lock
daemon/src/daemon.rs
daemon/src/peer.rs
daemon/src/peer/sync.rs
daemon/src/watcher.rs

These reconnections seem useful if you basically want to "stay connected" to your peer forever.
This PR restructures the peer code around a "ConnectionManager", which spawns an "EndpointActor", which can receive requests to make connections. When the EndpointActor decides that a reconnect makes sense, it will send such a message to itself.
It's the first time I needed to do some more "proper" error handling, because we want to be able to tell whether the reason for a failure was a timeout, or something else a couple of layers higher up. It's not really pretty.
(But maybe that's for a later PR?)
The main other failure reason I see is an authorization failure. The joining peer will not get any feedback on that failure, unfortunately – its next communication attempt will just fail. We could …

When a connection times out, reconnect

---

book/src/ignored-files.md
book/src/system-overview.md
book/src/workarounds.md
daemon/src/daemon.rs
daemon/src/document.rs
daemon/src/sandbox.rs
daemon/src/types.rs

Implements #192.
From manual testing, binary files now behave like text files.
For stress testing, I dropped a 1 GB video file in a directory, and this also worked. Initial syncing took maybe 30 seconds. Re-initiating a connection also. I think the code is currently not very optimized for this, and might touch the content of big files a bit more often than necessary. But I'd be fine with that, as a first step.

Support binary files

---

daemon/src/daemon.rs
daemon/src/document.rs
daemon/src/types.rs

Fixes #227 and #173.
On deletions/conflicting creations, the daemon will now communicate deletions to open editors, to make the content empty. It will also make sure that the files are re-created (to be consistent with them still being open in editors).

Handle file deletions when editor has file open

---

daemon/src/config.rs
daemon/src/daemon.rs
daemon/src/main.rs
daemon/src/sandbox.rs

Ignore VCS directories, and new way of ignoring .ethersync

---

vscode-plugin/package.json
vscode-plugin/src/extension.ts

When a remote edit replaces "x" with "XxX", VS Code will see a
TextDocumentChangeEvent that inserts two X's around the x. Because of
that, it's not possible to directly compare the edits.
Here's a proposed solution: Store the expected resulting content of the
document after the remote edit, then see if a local edit results in that
content.

vscode: Instead of expecting certain remote edits, expect their result
